### ISSUE TITLE
Convert JSON dump of Slack logs into readable format

### ISSUE THREAD

**Issue by kaushiksk** [IEEE-NITK/SummerProjects18#163]
Currently, the[ logs](https://github.com/IEEE-NITK/SummerProjects18/tree/master/UNIX) for the UNIX SMP contain the JSON dumps from slack. This is, however not very convenient to read through. A python script has to be written to read this JSON dump and write the log in a readable format, preferably `user: msg` and write it to a text file.

**Comment by mahirjain25** [comment]
@abhinavpy , look up how to parse json using the 'json' library in python. This should help.

https://stackoverflow.com/questions/2835559/parsing-values-from-a-json-file

**Comment by abhinavpy** [comment]
Thanks @mahirjain25

**Comment by abhinavpy** [comment]
How do I convert user id to username, is there like a database where slack stores userid-username or something like that? 
e.g.: "user": "UAH30B5KQ"
here "UAH30B5KQ" should be converted to "Abhinav P Y" when I'm printing on my text file.

**Comment by kaushiksk** [comment]
I'm not sure if that exists. You could check with the slack API once. For
now you can leave it as it is. We might have to hard code the mappings
though.

Regards,
Kaushik S Kalmady

**Comment by abhinavpy** [comment]
I think I have done it. Could someone please check it?
